name: Build and Deploy HelloWorldAuto

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore HelloWorldAuto.csproj

      - name: Build
        run: dotnet build HelloWorldAuto.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish HelloWorldAuto.csproj -c Release -o ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: HelloWorldAuto-publish
          path: ./publish

  deploy:
    runs-on: self-hosted   # Windows Server with IIS
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: HelloWorldAuto-publish
          path: C:\Users\devops-test2\Documents\publish

      - name: Deploy to IIS
        shell: pwsh
        run: |
          Import-Module WebAdministration

          $appPool   = "HelloWorldAuto"
          $siteName  = "HelloWorldAuto"
          $sitePath  = "C:\inetpub\wwwroot\HelloWorldAuto"
          $port      = 8081

          # Create or update App Pool
          if (-not (Test-Path "IIS:\AppPools\$appPool")) {
              New-WebAppPool -Name $appPool
          }
          Set-ItemProperty "IIS:\AppPools\$appPool" -Name managedRuntimeVersion -Value "v6.0"
          Start-WebAppPool -Name $appPool

          # Create site folder if not exists
          if (-not (Test-Path $sitePath)) {
              New-Item -ItemType Directory -Path $sitePath | Out-Null
          }

          # Clear old files
          if (Test-Path $sitePath) {
              Remove-Item "$sitePath\*" -Recurse -Force
          }

          # Copy new publish files
          Copy-Item "C:\Users\devops-test2\Documents\publish\*" $sitePath -Recurse

          # Create or update IIS Website
          if (Test-Path "IIS:\Sites\$siteName") {
              Stop-Website -Name $siteName
              Set-ItemProperty "IIS:\Sites\$siteName" -Name physicalPath -Value $sitePath
              Set-ItemProperty "IIS:\Sites\$siteName" -Name applicationPool -Value $appPool

              # Ensure binding is unique
              $existingBinding = Get-WebBinding -Name $siteName -ErrorAction SilentlyContinue | Where-Object { $_.bindingInformation -eq "*:$port:" }
              if (-not $existingBinding) {
                  New-WebBinding -Name $siteName -Protocol "http" -Port $port -IPAddress "*"
              }
          }
          else {
              New-Website -Name $siteName -Port $port -PhysicalPath $sitePath -ApplicationPool $appPool
          }

          # Start Website
          Start-Website -Name $siteName
